name: mongo #will be used for network auto naming and image names
services:
  app:
#    image: registry.digitalocean.com/juronja/nodejs-app
    image: 165.22.24.208:8083/nodejs-app #nexus repo
    container_name: webpage
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      MONGO_ADMIN_USER: ${MONGO_ADMIN_USER}
      MONGO_ADMIN_PASS: ${MONGO_ADMIN_PASS}
  db:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASS}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      start_period: 5s
    volumes:
      - mongodb:/data/db #Volume mapping for persistency
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - 8081:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASS}
#      ME_CONFIG_BASICAUTH_USERNAME: juronja
#      ME_CONFIG_BASICAUTH_PASSWORD: 0riPikica
      ME_CONFIG_MONGODB_SERVER: mongo 
#  nexus:
#    image: sonatype/nexus3
#    container_name: nexus
#    restart: unless-stopped
#    healthcheck:
#      test: curl http://localhost:8081/
#      interval: 10s
#      start_period: 5s
#    volumes:
#      - "nexus:/nexus-data"
#    ports:
#      - "8081:8081"
#      - "8082:8082"
volumes:
  mongodb: # It will prepend the project name
#  nexus:
